sonata_user:
    manager_type: orm
    class:
        user: App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          App\Application\Sonata\UserBundle\Admin\UserAdmin # there define your extended admin class
#            controller:     SonataUserBundle:UserCURD
#            translation:    SonataUserBundle
    

