# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'pl' 
#set language
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Security\ApiKeyUserProvider:
        arguments: ['@doctrine.orm.entity_manager']
    #['@fos_user.user_manager']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.games:
        class: App\Admin\GamesAdmin
        arguments: [~, App\Entity\Games, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Gry }
        public: true
        
    admin.tasks:
        class: App\Admin\TasksAdmin
        arguments: [~, App\Entity\Tasks, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Zadania }
        public: true
        
    admin.gametasks:
        class: App\Admin\GameTasksAdmin
        arguments: [~, App\Entity\GameTasks, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: GryZadania }
        public: true